import React, { useState, useEffect } from 'react'

export default function CopyFormLink({ onBack }) {
  const [formLink, setFormLink] = useState('')
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    // Generate a unique form link
    // In a real app, this would be generated by the backend
    const baseUrl = window.location.origin
    const uniqueId = `intern-form-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
    const link = `${baseUrl}/interns/register/${uniqueId}`
    setFormLink(link)
  }, [])

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formLink)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
      // Fallback for older browsers
      const textArea = document.createElement('textarea')
      textArea.value = formLink
      textArea.style.position = 'fixed'
      textArea.style.opacity = '0'
      document.body.appendChild(textArea)
      textArea.select()
      try {
        document.execCommand('copy')
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
      } catch (err) {
        console.error('Fallback copy failed:', err)
      }
      document.body.removeChild(textArea)
    }
  }

  return (
    <div className="space-y-3 sm:space-y-4">
      {/* Back Button */}
      <button
        onClick={onBack}
        className="flex items-center gap-1.5 sm:gap-2 text-xs sm:text-sm font-medium text-gray-600 hover:text-[#4C763B] transition-colors"
      >
        <svg className="h-3.5 w-3.5 sm:h-4 sm:w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
        </svg>
        Back to Options
      </button>

      {/* Form Link Section */}
      <div className="bg-white border-2 border-gray-200 rounded-lg sm:rounded-xl p-4 sm:p-5 lg:p-6">
        <div className="space-y-3 sm:space-y-4">
          {/* Icon and Title */}
          <div className="text-center space-y-1.5 sm:space-y-2">
            <div className="inline-flex items-center justify-center w-12 h-12 sm:w-14 sm:h-14 lg:w-16 lg:h-16 rounded-full bg-[#4C763B]/10">
              <svg className="h-6 w-6 sm:h-7 sm:w-7 lg:h-8 lg:w-8 text-[#4C763B]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.885 12.938 9 12.482 9 12c0-.482-.115-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
              </svg>
            </div>
            <h3 className="text-base sm:text-lg lg:text-xl font-bold text-gray-900">Form Link Generated</h3>
            <p className="text-xs sm:text-sm text-gray-600">
              Share this link with users to let them register themselves
            </p>
          </div>

          {/* Link Display */}
          <div className="space-y-1.5 sm:space-y-2">
            <label className="block text-xs sm:text-sm lg:text-base font-semibold text-gray-900">
              Form Registration Link
            </label>
            <div className="flex flex-col sm:flex-row gap-2 sm:gap-3">
              <input
                type="text"
                value={formLink}
                readOnly
                className="flex-1 px-3 sm:px-4 py-2 sm:py-2.5 text-xs sm:text-sm lg:text-base border-2 border-gray-200 rounded-lg bg-gray-50 focus:ring-2 focus:ring-[#4C763B] focus:border-[#4C763B] transition-colors"
              />
              <button
                onClick={handleCopy}
                className={`px-3 sm:px-4 lg:px-5 py-2 sm:py-2.5 text-xs sm:text-sm lg:text-base font-semibold text-white rounded-lg transition-colors shadow-sm hover:shadow-md flex items-center justify-center gap-1.5 sm:gap-2 ${
                  copied ? 'bg-green-600' : ''
                }`}
                style={copied ? {} : { backgroundColor: '#4C763B' }}
                onMouseEnter={(e) => {
                  if (!copied) {
                    e.currentTarget.style.backgroundColor = '#043915'
                  }
                }}
                onMouseLeave={(e) => {
                  if (!copied) {
                    e.currentTarget.style.backgroundColor = '#4C763B'
                  }
                }}
              >
                {copied ? (
                  <>
                    <svg className="h-3.5 w-3.5 sm:h-4 sm:w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    Copied!
                  </>
                ) : (
                  <>
                    <svg className="h-3.5 w-3.5 sm:h-4 sm:w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                    Copy Link
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Instructions */}
          <div className="pt-3 sm:pt-4 border-t border-gray-200 space-y-2 sm:space-y-2.5">
            <h4 className="text-xs sm:text-sm lg:text-base font-semibold text-gray-900">How to use:</h4>
            <ul className="space-y-1.5 sm:space-y-2 text-xs sm:text-sm text-gray-600">
              <li className="flex items-start gap-2">
                <span className="text-[#4C763B] font-bold mt-0.5">1.</span>
                <span>Copy the form link above</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#4C763B] font-bold mt-0.5">2.</span>
                <span>Share it with users via email, message, or any communication channel</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#4C763B] font-bold mt-0.5">3.</span>
                <span>Users can click the link and fill out their information themselves</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#4C763B] font-bold mt-0.5">4.</span>
                <span>Submitted data will automatically appear in your interns list</span>
              </li>
            </ul>
          </div>

          {/* QR Code Section (Optional - can be added later) */}
          <div className="pt-3 sm:pt-4 border-t border-gray-200">
            <p className="text-[10px] sm:text-xs text-gray-500 text-center">
              Tip: You can also generate a QR code for this link to make it easier to share
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

