/**
 * Mock data for interns
 */

export const mockInterns = [
  {
    id: 1,
    name: 'Alice Smith',
    email: 'alice.smith@example.com',
    domain: 'Web Development',
    status: 'Active',
    registeredDate: '2023-01-15',
    aptitudeScore: 85,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 2,
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    domain: 'Mobile Development',
    status: 'Active',
    registeredDate: '2023-02-20',
    aptitudeScore: 72,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    domain: 'UI/UX Design',
    status: 'Pending',
    registeredDate: '2023-03-10',
    aptitudeScore: null,
    aptitudeStatus: 'Pending',
    selectionStatus: 'Not Selected',
  },
  {
    id: 4,
    name: 'Diana Prince',
    email: 'diana.prince@example.com',
    domain: 'Data Science',
    status: 'Active',
    registeredDate: '2023-04-01',
    aptitudeScore: 91,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 5,
    name: 'Eve Adams',
    email: 'eve.adams@example.com',
    domain: 'Web Development',
    status: 'Inactive',
    registeredDate: '2023-05-05',
    aptitudeScore: 68,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Not Selected',
  },
  {
    id: 6,
    name: 'Frank Green',
    email: 'frank.green@example.com',
    domain: 'Web Development',
    status: 'Active',
    registeredDate: '2023-06-01',
    aptitudeScore: 78,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 7,
    name: 'Grace Hall',
    email: 'grace.hall@example.com',
    domain: 'Mobile Development',
    status: 'Active',
    registeredDate: '2023-07-10',
    aptitudeScore: 82,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 8,
    name: 'Henry King',
    email: 'henry.king@example.com',
    domain: 'Data Science',
    status: 'Active',
    registeredDate: '2023-08-12',
    aptitudeScore: 88,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 9,
    name: 'Ivy Martinez',
    email: 'ivy.martinez@example.com',
    domain: 'UI/UX Design',
    status: 'Pending',
    registeredDate: '2023-09-15',
    aptitudeScore: null,
    aptitudeStatus: 'Pending',
    selectionStatus: 'Not Selected',
  },
  {
    id: 10,
    name: 'Jack Wilson',
    email: 'jack.wilson@example.com',
    domain: 'Cloud Computing',
    status: 'Active',
    registeredDate: '2023-10-20',
    aptitudeScore: 75,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Not Selected',
  },
  {
    id: 11,
    name: 'Kate Lee',
    email: 'kate.lee@example.com',
    domain: 'Web Development',
    status: 'Active',
    registeredDate: '2023-11-05',
    aptitudeScore: 90,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Selected',
  },
  {
    id: 12,
    name: 'Liam Chen',
    email: 'liam.chen@example.com',
    domain: 'Mobile Development',
    status: 'Inactive',
    registeredDate: '2023-12-01',
    aptitudeScore: 65,
    aptitudeStatus: 'Completed',
    selectionStatus: 'Not Selected',
  },
]

