// Mock data for question papers
export const mockPaperSets = [
  {
    id: 1,
    name: 'Mathematics - Advanced Calculus',
    subject: 'Mathematics',
    year: '2024',
    semester: 'Spring',
    totalQuestions: 50,
    duration: 180,
    maxMarks: 100,
    createdAt: '2024-01-15',
    status: 'published',
    questions: [
      {
        text: 'What is the derivative of f(x) = x² + 3x - 5?',
        type: 'multiple-choice',
        weightage: 2,
        options: ['2x + 3', '2x - 3', 'x + 3', '2x² + 3'],
        correctOptions: [0],
      },
      {
        text: 'The limit of sin(x)/x as x approaches 0 is equal to 1.',
        type: 'true-false',
        weightage: 1,
        options: ['True', 'False'],
        correctOptions: [0],
      },
      {
        text: 'Explain the fundamental theorem of calculus in your own words.',
        type: 'multiple-choice', // short-answer removed
        weightage: 5,
        correctAnswer: 'The fundamental theorem of calculus states that differentiation and integration are inverse operations.',
      },
      {
        text: 'Which of the following are integration techniques?',
        type: 'multiple-choice',
        weightage: 3,
        options: ['Integration by parts', 'Substitution method', 'Long division', 'Partial fractions'],
        correctOptions: [0, 1, 3],
      },
    ],
  },
  {
    id: 2,
    name: 'Physics - Quantum Mechanics',
    subject: 'Physics',
    year: '2024',
    semester: 'Spring',
    totalQuestions: 45,
    duration: 150,
    maxMarks: 100,
    createdAt: '2024-01-20',
    status: 'draft',
  },
  {
    id: 3,
    name: 'Computer Science - Data Structures',
    subject: 'Computer Science',
    year: '2024',
    semester: 'Spring',
    totalQuestions: 60,
    duration: 120,
    maxMarks: 100,
    createdAt: '2024-02-01',
    status: 'published',
  },
  {
    id: 4,
    name: 'Chemistry - Organic Chemistry',
    subject: 'Chemistry',
    year: '2023',
    semester: 'Fall',
    totalQuestions: 40,
    duration: 180,
    maxMarks: 100,
    createdAt: '2023-11-10',
    status: 'published',
  },
  {
    id: 5,
    name: 'Biology - Cell Biology',
    subject: 'Biology',
    year: '2024',
    semester: 'Spring',
    totalQuestions: 55,
    duration: 150,
    maxMarks: 100,
    createdAt: '2024-02-15',
    status: 'draft',
  },
  {
    id: 6,
    name: 'English Literature - Modern Poetry',
    subject: 'English',
    year: '2024',
    semester: 'Spring',
    totalQuestions: 35,
    duration: 120,
    maxMarks: 100,
    createdAt: '2024-02-20',
    status: 'published',
  },
]

